results/v2.3.0-rc1/report_frdm_k64f_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_frdm_k82f_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_frdm_kl25z_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_frdm_kw41z_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_lpcxpresso54114_m4_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1010_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1015_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1020_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1050_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1060_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_mimxrt1064_evk_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_twr_ke18f_all_v2.3.0-rc1.xml, results/v2.3.0-rc1/report_twr_kv58f220m_all_v2.3.0-rc1.xml
trial
Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>
=> add v2.3.0-rc1 report

.github/workflows/check_results.yml, scripts/results_verification.py
The script is called by:
python3 results_verification.py -P <PATH_TO_REPORT VERSION> -Z <ZEPHYR_VERSION>
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> Add script for verification of junit xml reports

scripts/github_issue_template.tmpl, scripts/junit2issue.py
conver junit failures to github issue report
export REPORT_REPO="hakehuang/zephyr"
export GITHUB_ACCESS_TOKEN="\<your access token\>"
python3 ./junit2issus.py -v {version_folder} -i {xml file}
Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>
=> initial scripts to parser the junit format and submit to github issues

.github/workflows/check_results.yml
Increase these limits to 500
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
=> scripts: Increase allowed number of errors and failures in a report

.github/workflows/check_results.yml
=> scripts: increase reports size to 10 mb

.github/workflows/check_results.yml
Print out verification command
=> scripts: print out verification command

scripts/junit2issue.py
fix log length parse issue
Signed-off-by: Hake Huang <hake.huang@oss.nxp.com>
=> scriptes: fix log size check issue

scripts/junit2issue.py
the leading blank will be introplate as newlines, which will cause problem in filter issues.
Fixes [#69027](https://github.com/zephyrproject-rtos/zephyr/issues/69027)
=> fix the leading blank issue

scripts/results_verification.py
=> hwv2 naming fix

results/v4.0.0-2188-gfbdf6e346375/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-2188-gfbdf6e346375/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-2188-gfbdf6e346375: nxp weekly report

results/v4.0.0-2673-g0603637fc772/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-2673-g0603637fc772/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-2673-g0603637fc772: nxp weekly report

results/v4.0.0-2912-g8aa4aa7edf11/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-2912-g8aa4aa7edf11/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-2912-g8aa4aa7edf11: NXP weekly report

results/v4.0.0-3221-g72d0ed7782d1/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-3221-g72d0ed7782d1/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-3221-g72d0ed7782d1: nxp weekly report

results/v4.0.0-3683-gebbdb1068d3f/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-3683-gebbdb1068d3f/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-3683-gebbdb1068d3f: nxp weekly

results/v4.0.0-4499-gb5c5ba8c832b/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-4499-gb5c5ba8c832b/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-4499-gb5c5ba8c832b: NXP weekly board test

results/v4.0.0-4924-g0584f301396d/lpcxpresso54114_lpc54114_m4.xml, results/v4.0.0-4924-g0584f301396d/mimxrt1015_evk_mimxrt1015.xml
=> v4.0.0-4924-g0584f301396d: NXP weekly report

results/v4.1.0-rc1-41-g1280f432f4aa/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-rc1-41-g1280f432f4aa/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-rc1-41-g1280f432f4aa: NXP weekly test report

results/v4.1.0-rc2-27-g70f55bccf8af/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-rc2-27-g70f55bccf8af/mimxrt1015_evk_mimxrt1015.xml
NXP weekly report for v4.1.0-rc2-27-g70f55bccf8af
=> v4.1.0-rc2-27-g70f55bccf8af: NXP weekly test report

.github/workflows/check_results.yml, .github/workflows/compliance.yml, .github/workflows/process_results.yml, results/v4.1.0-rc3-13-g4f0b8d0daf40/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-rc3-13-g4f0b8d0daf40/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-rc3-13-g4f0b8d0daf40: NXP weekly report

results/v4.1.0-1189-g2587bc2aa34a/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-1189-g2587bc2aa34a/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-1189-g2587bc2aa34a: NXP weekly test

results/v4.1.0-1581-g6857dcabbf36/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-1581-g6857dcabbf36: NXP weekly report

results/v4.1.0-2039-g798db0f777d0/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-2039-g798db0f777d0/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-2039-g798db0f777d0: NXP weekly report

results/v4.1.0-2420-g8b54e8afa9f7/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-2420-g8b54e8afa9f7/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-2420-g8b54e8afa9f7: NXP weekly report

results/v4.1.0-2692-gb8d4a6aa592b/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-2692-gb8d4a6aa592b/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-2692-gb8d4a6aa592b: nxp weekly test

results/v4.1.0-3058-gcf6f9e3807ba/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-3058-gcf6f9e3807ba/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-3058-gcf6f9e3807ba: NXP weekly report

results/v4.1.0-3495-g4aa1ac9f969a/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-3495-g4aa1ac9f969a/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-3495-g4aa1ac9f969a: NXP weekly report

results/v4.1.0-3816-g958ef2288e01/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-3816-g958ef2288e01: NXP test report

results/v4.1.0-4691-g4d8ffcca93e9/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-4691-g4d8ffcca93e9/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-4691-g4d8ffcca93e9: NXP weekly report

results/v4.1.0-5940-gc4ed1c01eb54/lpcxpresso54114_lpc54114_m4.xml, results/v4.1.0-5940-gc4ed1c01eb54/mimxrt1015_evk_mimxrt1015.xml
=> v4.1.0-5940-gc4ed1c01eb54: NXP weekly report

results/v4.2.0-rc3-10-gf52d71c8cf5b/mimxrt1015_evk_mimxrt1015.xml
=> v4.2.0-rc3-10-gf52d71c8cf5b: NXP weekly report

results/v4.2.0-403-gee7834997bfa/mimxrt1015_evk_mimxrt1015.xml
=> v4.2.0-403-gee7834997bfa: NXP weekly report

results/v4.2.0-796-g1edc97cd043d/lpcxpresso54114_lpc54114_m4.xml, results/v4.2.0-796-g1edc97cd043d/mimxrt1015_evk_mimxrt1015.xml
=> v4.2.0-796-g1edc97cd043d: NXP weekly report

results/v4.2.0-1141-g2aca4ef0c236/lpcxpresso54114_lpc54114_m4.xml, results/v4.2.0-1141-g2aca4ef0c236/mimxrt1015_evk_mimxrt1015.xml
=> v4.2.0-1141-g2aca4ef0c236: NXP weekly report

results/v4.2.0-2622-g294f7e52c5f9/lpcxpresso54114_lpc54114_m4.xml, results/v4.2.0-2622-g294f7e52c5f9/mimxrt1015_evk_mimxrt1015.xml
=>  v4.2.0-2622-g294f7e52c5f9: NXP weekly report

results/v4.2.0-4192-gab2622fc2d1d/mimxrt1015_evk_mimxrt1015.xml
=> v4.2.0-4192-gab2622fc2d1d: NXP weekly
